spring:
  datasource:
    vent:
      url: jdbc:mysql://172.17.0.2:3306/vent?verifyServerCertificate=false&useSSL=true
      username: root
      password: ${MYSQL_DB_PASSWORD}
      driver-class-name: com.mysql.jdbc.Driver
      validation-query: select 1
    mastery:
      url: jdbc:mysql://172.17.0.2:3306/mastery?verifyServerCertificate=false&useSSL=true
      username: root
      password: ${MYSQL_DB_PASSWORD}
      driver-class-name: com.mysql.jdbc.Driver
      validation-query: select 1
    protus:
      url: jdbc:mysql://172.17.0.2:3306/protus?verifyServerCertificate=false&useSSL=true
      username: root
      password: ${MYSQL_DB_PASSWORD}
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: default #org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

mastery_endpoint: http://adapt2.sis.pitt.edu/aggregate2/GetContentLevels?grp=NorwaySpring2018&mod=user&sid=TEST&cid=352&usr=